### ISSUE TITLE
TransitionProvider messing up CSS...

### ISSUE THREAD

**Issue by rchrdnsh** [AndreasFaust/gatsby-plugin-transitions#3]
My layout normally stretches the width of the remaining space using CSS Grid, like so...

<img width="1440" alt="Screenshot 2019-05-25 15 03 39" src="https://user-images.githubusercontent.com/7884263/58374999-50913f80-7efe-11e9-813c-a3c339ad6981.png">

But after simply adding `<TransitionProvider>` this happens...

<img width="1440" alt="Screenshot 2019-05-25 15 01 32" src="https://user-images.githubusercontent.com/7884263/58374992-2a6b9f80-7efe-11e9-91e6-13282231b7fd.png">

Not sure how to fix it, but this is my code:

```js
<Main>
  {children}
</Main>
```

to:

```js
<Main>
  <TransitionProvider location={location}>{children}</TransitionProvider>
</Main>
```

and here is my 'css' for `<Main>`:

```js
const Main = styled.main`
  margin: 0;
  padding: 0;
  grid-column: 1 / 4;
  grid-row: 1 / 3;
  background: white;
  overflow-y: scroll;
  -webkit-overflow-scrolling: touch;
  z-index: 0;
  display: grid;
  grid-template-columns: 
    minmax(1rem, 1fr) 
    minmax(1rem, 40rem) 
    minmax(1rem, 1fr);

  @media (min-width: 50rem) {
    grid-column: 2 / 3;
    grid-row: 1 / 5;
  }
`;
```

and adding `grid-column: 1 / 4;` to the `<TransitionProvider>` does not seem to solve it.

**Comment by AndreasFaust** [comment]
Maybe you have to position the `views`-wrapper on the grid?
You can do this by the class "view" or using the new `style-prop. I released it a minute ago, so be sure to update gatsby-plugin-transitions!
```
<TransitionProvider location={location} style={{ grid-column: 1 / 4 }}>
  {children}
</TransitionProvider>
```

**Comment by rchrdnsh** [comment]
I updated and copied your code, but it is still not working correctly. I had to change `grid-column: 1 / 4` into gridColumn: 1 / 4` so that it would be valid CSS-in-JS, but it complied, then looks exactly the same :-(

Shouldn't regular css work on the component?

**Comment by AndreasFaust** [comment]
Of course you can style it with regular CSS. It has the class `views`. 
I am sorry, but with the code you provide, I can just make vage guesses. Could you send me a link or create a repo?

**Comment by rchrdnsh** [comment]
yeah, let me figure that out...

**Comment by rchrdnsh** [comment]
ok, I made a repo...pretty new to doing this, so I hope I did it ok :-)

https://github.com/rchrdnsh/alma-plugin-tranistions

**Comment by rchrdnsh** [comment]
ok, figured it out. `.views` worked in the css, I just had a dumb typo :-(

Anyway, thank you for your expedient help! XD
